require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_rails.yml

AllCops:
  CacheRootDirectory: tmp/cache
  AllowSymlinksInCacheRootDirectory: true
  MaxFilesInCache: 30000
  TargetRubyVersion: 2.6

  Exclude:
    - .bundle/**/*
    - bin/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/bundle/**/*
    - vendor/cache/**/*
    - node_modules/**/*
    - db/schema.rb
    - script/one_offs/data_sanitiser_config.rb

Capybara/FeatureMethods:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HeredocIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - config/unicorn.rb
    - config/docker_unicorn.rb
    - config/puma.rb
    - config/docker_puma.rb

Lint/UnusedBlockArgument:
  Enabled: false

Lint/Void:
  Exclude:
    - lib/future_learn/image_quality.rb

Lint/UnusedMethodArgument:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/UriRegexp:
  Enabled: true

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Exclude:
    - spec/support/matchers/params_hash_matcher.rb

Naming/FileName:
  Exclude:
    - bin/**
    - Capfile
    - Gemfile

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/AnyInstance:
  Enabled: true
  Exclude:
    - spec/features/authenticating_with_a_saml_identity_provider_spec.rb
    - spec/features/authenticating_with_futurelearns_gsuite_as_the_identity_provider_spec.rb
    - spec/features/saml_enrolment_spec.rb

RSpec/ContextWording:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Exclude:
    - spec/api_helpers/partners/**/*
    - spec/apis/partners/**/*
    - spec/controllers/comment_routing_spec.rb
    - spec/controllers/comment_saving_spec.rb
    - spec/controllers/restrict_access_to_step_spec.rb
    - spec/controllers/run_lookup_spec.rb
    - spec/controllers/step_within_run_lookup_spec.rb
    - spec/lib/future_learn/cops/**/*
  CustomTransform:
    MySQLVersionChecker: mysql_version_checker

RSpec/VariableName:
  Enabled: false

RSpec/VariableDefinition:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - lib/future_learn/webpack.rb

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/CaseEquality:
  Exclude:
    - spec/support/controller_support.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExpandPathArguments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: true
  EnforcedStyle: strict

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/PreferredHashMethods:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantFreeze:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/SingleLineBlockParams:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/TrailingCommaInArguments:
  Exclude:
    - 'spec/services/transcript/generator_spec.rb'

Style/TrivialAccessors:
  AllowPredicates: True

Style/RedundantPercentQ:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Migration/DepartmentName:
  Enabled: true
